spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://52.78.19.127:3306/spring?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
#    username: root
#    password: aqaq2114456178!
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create

springdoc:
  swagger-ui:
    path: /docs/swagger